from django.urls import path
from .views import (
    getting_items,
    getting_all_customers,
    testimonial_page,
    product_page,
    productlikes,
    getting_form,
    posting_data,
    post_comment,
    email_submittions,
    postlike,
    products_page,
    likescount,
    user_profile,
    comments,
    dataquary,
    testimonials,
    videoplayer,
    products_details,
    posting_items,
    posting_address,
    getting_list,
    posting_list,
    user_amount,
    close_user,
    getting_user_products,
    checking_user_coupon,
    user_coupon_set,
    user_pricestate,
    user_coupon_get,
    user_priceget,
    free_gift,
    amdinseeproduct,
    admin_search,
    amdinqueryproduct,
    adminproductsubmit,
    adminseefree,
    adminfreesearch,
    adminqueryfreeproduct,
    adminfreegiftsubmit,
    admindeletefree,
    admindeleteproduct,
    adminsummitpricing,
    adminseeclosedcustomers,
    adminsearchclose,
    adminqueryclientdetails,
    admingetclientproducts,
    adminupdateclientproduct,
    admindeletefreegift,
    admingettotalprocessing,
    admingetnavnumbers,
    admingetallcontactclients,
    admin_update_contact_client,
    admin_see_testimonials,
    admin_testimonial_submit,
    admin_see_coupons,
    admin_query_count,
    admin_search_coupons,
    admin_coupon_submit,
    admin_login_status,
    thank_you_video,
    query_search_products,
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("product/<slug:pk>/", products_details),
    path("testimonial/", testimonial_page),
    path("customers/", getting_all_customers),
    path("comments/<int:pk>/", comments),
    path("dataquary/<str:pk>/", dataquary),
    path("loginuser/", user_profile),
    path("testimonials/", testimonials),
    path("videoplay/", videoplayer),
    path("productlikes/<int:pk>/", productlikes),
    path("postlike/<int:pk>/", postlike),
    path("postcomment/<int:pk>/", post_comment),
    path("likescount/<int:pk>/", likescount),
    path("newsletter/", email_submittions),
    path("gettingform/", getting_form),
    path("postingform/", posting_data),
    path("postingaddress/", posting_address),
    path("gettingitems/", getting_items),
    path("postingitems/", posting_items),
    path("gettinglists/", getting_list),
    path("posttinglists/", posting_list),
    path("gettingamount/", user_amount),
    path("productlist/", getting_user_products),
    path("user-coupon/", checking_user_coupon),
    path("couponstate/", user_coupon_set),
    path("couponget/", user_coupon_get),
    path("close-user/", close_user),
    path("pricestate/", user_pricestate),
    path("priceget/", user_priceget),
    path("freegift/", free_gift),
    path("adminsearch/<str:pk>/", admin_search),
    path("amdinseeproduct/", amdinseeproduct),
    path("admindeleteproduct/<int:pk>/", admindeleteproduct),
    path("adminseefreegift/", adminseefree),
    path("adminqueryfreeproduct/<int:pk>/", adminqueryfreeproduct),
    path("adminfreegiftsubmit/", adminfreegiftsubmit),
    path("admindeletefree/<int:pk>/", admindeletefree),
    path("adminfreesearch/<str:pk>/", adminfreesearch),
    path("amdinqueryproduct/<int:pk>/", amdinqueryproduct),
    path("adminproductsubmit/", adminproductsubmit),
    path("adminsummitpricing/", adminsummitpricing),
    path("adminseeclosedcustomers/", adminseeclosedcustomers),
    path("adminsearchclosecustomer/<str:pk>/", adminsearchclose),
    path("adminqueryclientdetails/<int:pk>/", adminqueryclientdetails),
    path("admingetclientproducts/<int:pk>/", admingetclientproducts),
    path("adminupdateclientproduct/", adminupdateclientproduct),
    path("admindeletefreegift/<int:pk>/", admindeletefreegift),
    path("admingettotalprocessing/<int:pk>/", admingettotalprocessing),
    path("admingetnavnumbers/", admingetnavnumbers),
    path("admingetallcontactclients/", admingetallcontactclients),
    path("adminupdatecontactclient/", admin_update_contact_client),
    path("adminseetestimonials/", admin_see_testimonials),
    path("admintestimonialsubmit/", admin_testimonial_submit),
    path("adminseecoupons/", admin_see_coupons),
    path("adminquerycount/<int:pk>/", admin_query_count),
    path("adminsearchcoupons/<str:pk>/", admin_search_coupons),
    path("admincouponsubmit/", admin_coupon_submit),
    path("adminlogin/", admin_login_status),
    path("thankyouvideo/", thank_you_video),
    path("querysearchproducts/<str:pk>/", query_search_products),
    path("", product_page),
    path("<str:pk>/", products_page),
]
