# Generated by Django 4.2.1 on 2023-07-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0002_alter_products_zero_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("processing", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="dollar_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="measurement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="products",
            name="naira_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="total_money",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserClosed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_of_delivery", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("all_total", models.FloatField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("complete", models.BooleanField(default=False)),
                (
                    "product_items",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yeyebackend.productitems",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productitems",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.products",
            ),
        ),
        migrations.AddField(
            model_name="productitems",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.users",
            ),
        ),
        migrations.CreateModel(
            name="FreeGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_to_pass", models.FloatField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yeyebackend.products",
                    ),
                ),
            ],
        ),
    ]
