# Generated by Django 4.2.1 on 2023-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0002_alter_products_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="liked",
            field=models.ManyToManyField(to="yeyebackend.users"),
        ),
    ]
