# Generated by Django 4.2.1 on 2023-07-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0003_productitems_products_dollar_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="unique",
            new_name="special",
        ),
    ]
