# Generated by Django 4.2.1 on 2023-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0004_rename_unique_products_special"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="old_dollar_price",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
