# Generated by Django 4.2.1 on 2023-05-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0004_alter_products_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
