# Generated by Django 4.2.1 on 2023-05-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0005_comments_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="Comment",
            new_name="comment",
        ),
    ]
