# Generated by Django 4.2.1 on 2023-05-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0006_rename_comment_comments_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
