# Generated by Django 4.2.1 on 2023-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0006_useritemsactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="gmail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
