# Generated by Django 4.2.1 on 2023-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0007_alter_users_gmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritemsactions",
            name="measurement",
            field=models.BooleanField(default=False),
        ),
    ]
