# Generated by Django 4.2.1 on 2023-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0007_alter_users_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="videoPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video", models.FileField(upload_to="")),
            ],
        ),
    ]
