# Generated by Django 4.2.1 on 2023-05-22 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0008_videoplayer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="created_at",
        ),
        migrations.AddField(
            model_name="comments",
            name="checkedlast",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
