# Generated by Django 4.2.1 on 2023-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0008_useritemsactions_measurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
