# Generated by Django 4.2.1 on 2023-05-29 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0009_remove_comments_created_at_comments_checkedlast"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
