# Generated by Django 4.2.1 on 2023-08-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0010_useritemslists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userclosed",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userclosed",
            name="name",
        ),
        migrations.RemoveField(
            model_name="userclosed",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="userclosed",
            name="place_of_delivery",
        ),
        migrations.AddField(
            model_name="userclosed",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.users",
            ),
        ),
    ]
