# Generated by Django 4.2.1 on 2023-05-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0010_users_created_at_users_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="old_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comments",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.products",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.users",
            ),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="client",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.comments",
            ),
        ),
    ]
