# Generated by Django 4.2.1 on 2023-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0011_remove_userclosed_email_remove_userclosed_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userclosed",
            name="product_items",
        ),
        migrations.AlterField(
            model_name="productitems",
            name="processing",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
