# Generated by Django 4.2.1 on 2023-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0011_products_old_price_alter_comments_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonials",
            name="client",
        ),
        migrations.AddField(
            model_name="testimonials",
            name="client_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testimonials",
            name="client_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="testimonials",
            name="client_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
