# Generated by Django 4.2.1 on 2023-08-21 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0012_remove_userclosed_product_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitems",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productitems",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userclosed",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userclosed",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
