# Generated by Django 4.2.1 on 2023-05-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0012_remove_testimonials_client_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testimonials",
        ),
    ]
