# Generated by Django 4.2.1 on 2023-08-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "yeyebackend",
            "0013_productitems_created_at_productitems_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productitems",
            name="userclosed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.userclosed",
            ),
        ),
    ]
