# Generated by Django 4.2.1 on 2023-05-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0013_delete_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("client_comment", models.TextField(blank=True, null=True)),
                (
                    "client_picture",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
    ]
