# Generated by Django 4.2.1 on 2023-08-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0014_productitems_userclosed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclosed",
            name="shipping_call",
            field=models.BooleanField(default=False),
        ),
    ]
