# Generated by Django 4.2.1 on 2023-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0014_testimonials"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="decription_span",
            field=models.TextField(blank=True, null=True),
        ),
    ]
