# Generated by Django 4.2.1 on 2023-06-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0015_products_decription_span"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="decription_span",
            new_name="description_span",
        ),
    ]
