# Generated by Django 4.2.1 on 2023-06-08 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0016_rename_decription_span_products_description_span"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="Meta_Title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="Meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="catalog",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="hot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="products",
            name="materials_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="unique",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="products",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
