# Generated by Django 4.2.1 on 2023-08-23 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0016_coupons_usercoupons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupons",
            name="coupon_number",
        ),
        migrations.AddField(
            model_name="coupons",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coupons",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
