# Generated by Django 4.2.1 on 2023-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0017_products_meta_title_products_meta_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="old_price",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.CharField(),
        ),
    ]
