# Generated by Django 4.2.1 on 2023-08-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "yeyebackend",
            "0017_remove_coupons_coupon_number_coupons_created_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yeyebackend.users",
                    ),
                ),
            ],
        ),
    ]
