# Generated by Django 4.2.1 on 2023-06-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0018_alter_products_old_price_alter_products_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="Currency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="zero_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="old_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.FloatField(),
        ),
    ]
