# Generated by Django 4.2.1 on 2023-08-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0019_pricestate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricestate",
            name="state",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
