# Generated by Django 4.2.1 on 2023-06-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0019_products_currency_products_zero_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="liked",
            field=models.ManyToManyField(blank=True, null=True, to="yeyebackend.users"),
        ),
    ]
