# Generated by Django 4.2.1 on 2023-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0020_alter_products_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="liked",
            field=models.ManyToManyField(blank=True, to="yeyebackend.users"),
        ),
    ]
