# Generated by Django 4.2.1 on 2023-08-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0021_alter_couponstate_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricestate",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
