# Generated by Django 4.2.1 on 2023-08-27 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0022_pricestate_shipping_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freegift",
            name="product",
        ),
        migrations.AddField(
            model_name="freegift",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="freegift",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="freegift",
            name="naira_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freegift",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="freegift",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freegift",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productitems",
            name="freegift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.freegift",
            ),
        ),
    ]
