# Generated by Django 4.2.1 on 2023-08-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0023_remove_freegift_product_freegift_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freegift",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
