# Generated by Django 4.2.1 on 2023-08-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0024_alter_freegift_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
