# Generated by Django 4.2.1 on 2023-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0026_usercartprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="catalog",
        ),
        migrations.RemoveField(
            model_name="products",
            name="color",
        ),
        migrations.RemoveField(
            model_name="products",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="products",
            name="dollar_price",
        ),
        migrations.RemoveField(
            model_name="products",
            name="materials_type",
        ),
        migrations.RemoveField(
            model_name="products",
            name="naira_price",
        ),
        migrations.RemoveField(
            model_name="products",
            name="old_dollar_price",
        ),
        migrations.RemoveField(
            model_name="products",
            name="zero_price",
        ),
        migrations.AddField(
            model_name="products",
            name="Vendor_contact",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="products",
            name="old_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
