# Generated by Django 4.2.1 on 2023-09-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0027_remove_products_catalog_remove_products_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="gender",
            new_name="type",
        ),
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="out_of_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="products",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="vendor_location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
