# Generated by Django 4.2.1 on 2023-09-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0028_rename_gender_products_type_products_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freegift",
            name="Vendor_contact",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freegift",
            name="vendor_image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="freegift",
            name="vendor_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freegift",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="vendor_image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="useritemsactions",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.products",
            ),
        ),
        migrations.AlterField(
            model_name="useritemslists",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yeyebackend.products",
            ),
        ),
    ]
