# Generated by Django 4.2.1 on 2023-09-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0029_freegift_vendor_contact_freegift_vendor_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclosed",
            name="new_user",
            field=models.BooleanField(default=False),
        ),
    ]
