# Generated by Django 4.2.1 on 2023-09-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0030_userclosed_new_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupons",
            name="owner_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="coupons",
            name="owner_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="coupons",
            name="owner_phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productitems",
            name="discussion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productitems",
            name="schedule_date",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="discussion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="new_client",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="schedule_date",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
