# Generated by Django 4.2.1 on 2023-09-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0031_coupons_owner_email_coupons_owner_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="vendor_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
