# Generated by Django 4.2.1 on 2023-09-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0032_products_vendor_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclosed",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
