# Generated by Django 4.2.1 on 2023-09-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0033_userclosed_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freegift",
            name="naira_price",
        ),
        migrations.AlterField(
            model_name="videoplayer",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="videoplayer",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
