# Generated by Django 4.2.1 on 2023-09-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "yeyebackend",
            "0034_remove_freegift_naira_price_alter_videoplayer_title_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="complete",
            new_name="follow_up",
        ),
        migrations.RemoveField(
            model_name="users",
            name="new_client",
        ),
    ]
