# Generated by Django 4.2.1 on 2023-09-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yeyebackend", "0036_testimonials_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
